### ISSUE TITLE
Logging error - "possible formatting error"

### ISSUE THREAD

**Issue by lnfecteDru** [Gobot1234/steam.py#109]
### Summary

When logging enabled, on every action 'logging error' is printed. I'm getting this error when using GC client.

### Reproduction Steps

```python
import json
import logging
import steam
from steam.ext import tf2

logger = logging.getLogger('steam')
logger.setLevel(logging.DEBUG)
formatter = logging.Formatter('%(asctime)s:%(levelname)s:%(name)s: %(message)s')
handler = logging.FileHandler(filename='steam.log', encoding='utf-8', mode='w')
handler.setFormatter(formatter)
logger.addHandler(handler)

with open('credentials.json', 'r') as f:
    credentials = json.load(f)
bot = tf2.Client(state=steam.PersonaState.Online)
bot.run(**credentials)
```

### Expected Results

_Nothing_

### Actual Results

--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\lnfecteD\miniconda3\envs\tfgc\lib\logging\__init__.py", line 1085, in emit
    msg = self.format(record)
  File "C:\Users\lnfecteD\miniconda3\envs\tfgc\lib\logging\__init__.py", line 929, in format
    return fmt.format(record)
  File "C:\Users\lnfecteD\miniconda3\envs\tfgc\lib\logging\__init__.py", line 668, in format
    record.message = record.getMessage()
  File "C:\Users\lnfecteD\miniconda3\envs\tfgc\lib\logging\__init__.py", line 373, in getMessage
    msg = msg % self.args
  File "C:\Users\lnfecteD\miniconda3\envs\tfgc\lib\site-packages\steam\protobufs\__init__.py", line 87, in __repr__
    resolved.extend(f"{k}={v!r}" for k, v in self.body.to_dict(do_nothing_case).items())
  File "C:\Users\lnfecteD\miniconda3\envs\tfgc\lib\site-packages\steam\protobufs\struct_messages.py", line 35, in to_dict
    return {key: getattr(self, key) for key in self.__annotations__}
AttributeError: 'CacheSubscribedCheck' object has no attribute '__annotations__'
Call stack:
  File "d:/Workspace/Python/tf_crafting/issue_thread/craft_logging.py", line 16, in <module>
    bot.run(**credentials)
  File "C:\Users\lnfecteD\miniconda3\envs\tfgc\lib\site-packages\steam\client.py", line 367, in run
    asyncio.run(runner())
  File "C:\Users\lnfecteD\miniconda3\envs\tfgc\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\lnfecteD\miniconda3\envs\tfgc\lib\asyncio\base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "C:\Users\lnfecteD\miniconda3\envs\tfgc\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\lnfecteD\miniconda3\envs\tfgc\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "C:\Users\lnfecteD\miniconda3\envs\tfgc\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "C:\Users\lnfecteD\miniconda3\envs\tfgc\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\lnfecteD\miniconda3\envs\tfgc\lib\site-packages\steam\utils.py", line 765, in maybe_coroutine
    return await value
  File "C:\Users\lnfecteD\miniconda3\envs\tfgc\lib\site-packages\steam\ext\_gc\state.py", line 60, in parse_gc_message
    log.debug("Socket has received GC message %r from the websocket.", gc_msg)
Unable to print the message and arguments - possible formatting error.
Use the traceback above to help find the error.

### System Information

python version: 3.8.13
steam.py version: 0.9.0a2178+g7721597
aiohttp version: 3.8.1
betterproto version: 2.0.0b4
operating system info: Windows-10-10.0.19044-SP0

### Checklist

- [X] I have searched the issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my username/password/secrets from display, if visible.

**Comment by Gobot1234** [comment]
Thanks for the report
