### ISSUE TITLE
WSException when trying to add an emoticon to a message

### ISSUE THREAD

**Issue by truenicoco** [Gobot1234/steam.py#200]
### Summary

Cannot add emoticon reaction

### Reproduction Steps

Call `add_emoticon()` on a message, eg:

```py
class client(steam.Client):
    async def on_message(self, message: steam.Message):
        await message.add_emoticon(self.emoticons[0])
```

### Expected Results

`steam.py` should add an emoji to the message

### Actual Results

```
DEBUG:steam.gateway:Socket has received CMsgMulti(message_body=bytearray(b'U\x00\x00\x00\x93\x00\x00\x80M\x00\x00\x00\t \xa9H\x05\x01\x00\x10\x01\x10\xcb\x95\xce\x9d\xff\xff\xff\xff\xff\x01Y\x05\x00\x00\x00\x00\x00\x00\x00b&FriendMessages.UpdateMessageReaction#1h\x0f\x88\x01\x01\xc0\x01\x01')) from the websocket.
DEBUG:steam.client:Dispatching event socket_receive
DEBUG:steam.gateway:Received a multi
DEBUG:steam.gateway:Socket has received UpdateMessageReactionResponse() from the websocket.
DEBUG:steam.client:Dispatching event socket_receive
DEBUG:steam.state:Got a UM 'FriendMessages.UpdateMessageReaction#1' that we don't handle UpdateMessageReactionResponse()
Ignoring exception in on_message
Traceback (most recent call last):
  File "/venv/lib/python3.11/site-packages/steam/client.py", line 290, in _run_event
    await coro(*args, **kwargs)
  File "/venv/lib/python3.11/site-packages/slidge/plugins/steam/client.py", line 67, in on_message
    await message.add_emoticon(self.emoticons[0])
  File "/venv/lib/python3.11/site-packages/steam/message.py", line 49, in add_emoticon
    await self._state.react_to_user_message(
  File "/venv/lib/python3.11/site-packages/steam/state.py", line 602, in react_to_user_message
    raise WSException(msg)
steam.errors.WSException: The request FriendMessages.UpdateMessageReaction#1 failed. (error code: Result.AccessDenied)
```

### System Information

Using e74f39761be65c3419bc893bc0e4d3cf3aaf9dc8

```
nicoco@hummp ~/s/p/x/slidge (steamio)> python3 -m steam
Traceback (most recent call last):
  File "/home/nicoco/dl/Python-3.10.11/Lib/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/nicoco/dl/Python-3.10.11/Lib/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/home/nicoco/dl/Python-3.10.11/Lib/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/home/nicoco/.cache/pypoetry/virtualenvs/slidge-AjQFdees-py3.10/lib/python3.10/site-packages/steam/__init__.py", line 10, in <module>
    from . import abc as abc, guard as guard, utils as utils
  File "/home/nicoco/.cache/pypoetry/virtualenvs/slidge-AjQFdees-py3.10/lib/python3.10/site-packages/steam/abc.py", line 18, in <module>
    from . import utils
  File "/home/nicoco/.cache/pypoetry/virtualenvs/slidge-AjQFdees-py3.10/lib/python3.10/site-packages/steam/utils.py", line 47, in <module>
    from ._const import JSON_LOADS, MISSING, URL
  File "/home/nicoco/.cache/pypoetry/virtualenvs/slidge-AjQFdees-py3.10/lib/python3.10/site-packages/steam/_const.py", line 107, in <module>
    from taskgroup import TaskGroup as TaskGroup, timeout as timeout
ModuleNotFoundError: No module named 'taskgroup'


### Checklist

- [X] I have searched the issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my username/password/secrets from display, if visible.

**Comment by Gobot1234** [comment]
Thanks for the bug report
