### ISSUE TITLE
Unable to login with client.Client.run() method

### ISSUE THREAD

**Issue by pstryczke** [Gobot1234/steam.py#377]
### Summary

Unable to login with client.Client.run() method

### Reproduction Steps

Trying to login with vaild username and password using `run(USERNAME, PASSWORD)` method of `client.Client` instance.

### Expected Results

Successful login after providing valid username and password

### Actual Results

`KeyError` observed during executing `run(USERNAME, PASSWORD)` method:
```
Traceback (most recent call last):
  File "C:\user_mrpst\PycharmProjects\SteamPrices\steam_price_getter.py", line 265, in <module>
    temp.run(USERNAME, PASSWORD)
  File "C:\user_mrpst\PycharmProjects\SteamPrices\venv\Lib\site-packages\steam\client.py", line 372, in run
    asyncio.run(runner())
  File "C:\Python\Python3.11\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Python\Python3.11\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\Python3.11\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\user_mrpst\PycharmProjects\SteamPrices\venv\Lib\site-packages\steam\client.py", line 363, in runner
    await self.start(*args, **kwargs)
  File "C:\user_mrpst\PycharmProjects\SteamPrices\venv\Lib\site-packages\steam\client.py", line 465, in start
    await self.login(username, password, shared_secret=shared_secret)
  File "C:\user_mrpst\PycharmProjects\SteamPrices\venv\Lib\site-packages\steam\client.py", line 403, in login
    await self.http.login(username, password, shared_secret=shared_secret)
  File "C:\user_mrpst\PycharmProjects\SteamPrices\venv\Lib\site-packages\steam\http.py", line 189, in login
    for url in resp["transfer_urls"]:
               ~~~~^^^^^^^^^^^^^^^^^
KeyError: 'transfer_urls'
```

Script was working fine few hours ago.

### System Information

```
python version: 3.11.2
steam.py version: 0.9.9
aiohttp version: 3.8.4
betterproto version: 2.0.0b4
operating system info: Windows-10-10.0.19045-SP0
```

### Checklist

- [X] I have searched the issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my username, password, shared/identity secrets and refresh/access tokens from display, if visible.

**Comment by Gobot1234** [comment]
Steam has removed the old methods of logging in you need to use V1. There's nothing I can really do here.
