### ISSUE TITLE
Spray in inventory raises None Type Error

### ISSUE THREAD

**Issue by Tom-jm03** [Gobot1234/steam.py#483]
### Summary

Spray in inventory raises None Type Error

### Reproduction Steps

Have the Spray 1734 (Sorry spray_std_sorry) in your inventory.

### Expected Results

No None Type Error

### Actual Results

```python
Task exception was never retrieved
future: <Task finished name='steam.py GC 730: parse_gc_client_connect' coro=<GCState.parse_gc_client_connect() done, defined at /home/ubuntu/discordbots/python/csgo-xp-bot/env/lib/python3.11/site-packages/steam/ext/csgo/state.py:95> exception=TypeError("a bytes-like object is required, not 'NoneType'")>
Traceback (most recent call last):
  File "/home/ubuntu/discordbots/python/csgo-xp-bot/env/lib/python3.11/site-packages/steam/ext/csgo/state.py", line 100, in parse_gc_client_connect
    await self.update_backpack(*(base.Item().parse(item_data) for item_data in cache.object_data))
  File "/home/ubuntu/discordbots/python/csgo-xp-bot/env/lib/python3.11/site-packages/steam/ext/csgo/state.py", line 175, in update_backpack
    slot=READ_U32(utils.get(gc_item.attribute, def_index=290 + i)),  # type: ignore
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/discordbots/python/csgo-xp-bot/env/lib/python3.11/site-packages/steam/_const.py", line 130, in READ_U32
    (u32,) = unpacker(s)
             ^^^^^^^^^^^
TypeError: a bytes-like object is required, not 'NoneType

```

### System Information

```
python version: 3.11.0rc1
steam.py version: 1.0.1
aiohttp version: 3.8.5
betterproto version: 2.0.0b6
operating system info: Linux-5.15.0-94-generic-x86_64-with-glibc2.35
````

### Checklist

- [X] I have searched the issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my username, password, shared/identity secrets and refresh/access tokens from display, if visible.

**Comment by Tom-jm03** [comment]
Another item:

```python
TypeError: a bytes-like object is required, not 'NoneType'
Task exception was never retrieved
future: <Task finished name='steam.py GC 730: parse_gc_client_connect' coro=<GCS                                                                                                                                                                                                             tate.parse_gc_client_connect() done, defined at /usr/local/lib/python3.11/site-p                                                                                                                                                                                                             ackages/steam/ext/csgo/state.py:95> exception=TypeError("a bytes-like object is                                                                                                                                                                                                              required, not 'NoneType'")>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/steam/ext/csgo/state.py", line 1                                                                                                                                                                                                             00, in parse_gc_client_connect
    await self.update_backpack(*(base.Item().parse(item_data) for item_data in c                                                                                                                                                                                                             ache.object_data))
  File "/usr/local/lib/python3.11/site-packages/steam/ext/csgo/state.py", line 1                                                                                                                                                                                                             73, in update_backpack
    slot=READ_U32(utils.get(gc_item.attribute, def_index=290 + i)),  # type: ign                                                                                                                                                                                                             ore
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/steam/_const.py", line 130, in R                                                                                                                                                                                                             EAD_U32
    (u32,) = unpacker(s)
             ^^^^^^^^^^^
TypeError: a bytes-like object is required, not 'NoneType'
```
